name: Lint Configs
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint YAML
        uses: ibiqlik/action-yamllint@v3
      - name: Lint Markdown
        uses: avto-dev/markdown-lint@v1
